<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApexLab.Application\ApexLab.Application.csproj" />
    <ProjectReference Include="..\ApexLab.Domain\ApexLab.Domain.csproj" />
    <ProjectReference Include="..\ApexLab.Telemetry.Abstractions\ApexLab.Telemetry.Abstractions.csproj" />
  </ItemGroup>

</Project>
